config:
  project_repos:
    dispel4py:
      repo: 'https://github.com/davrodgon/dispel4py.git'
      branch: eosc-synergy

sqa_criteria:
  qc_licensing:
    path: License.txt
  qc_style:
    repos:
      dispel4py:
        executor:
          container: dispel4py-testing
          tox:
            tox_file: /dispel4py-testing/tox.ini
            testenv:
              - stylecheck


