config:
  project_repos:
    dispel4py:
      repo: 'https://github.com/davrodgon/dispel4py.git'
      branch: eosc-synergy

sqa_criteria:
  qc_accessibility:
    repos:
      dispel4py:
        container: dispel4py-testing        
        commands:
          - checkCitable.py davrodgon/dispel4py
  qc_licensing:
    repos:
      dispel4py:
        commands: 
          - checkLicense.py davrodgon/dispel4py


