config:
  project_repos:
    dispel4py:
      repo: 'https://github.com/davrodgon/dispel4py.git'
      branch: eosc-synergy

sqa_criteria:
  qc_licensing:
    repos:
      dispel4py:
        container: dispel4py-testing
        commands: 
          - python setup.py build_sphinx 
  qc_style:
    repos:
      dispel4py:
        container: dispel4py-testing
        tox:
          tox_file: /dispel4py-testing/tox.ini
          testenv:
            - stylecheck
  qc_coverage:
    repos:
      deepaas:
        container: dispel4py-testing
        tox:
          tox_file: /dispel4py-testing/tox.ini
          testenv: 
            - cobertura

  qc_security:
    repos:
      deepaas:
        container: dispel4py-testing
        tox:
          tox_file: /dispel4py-testing/tox.ini
          testenv:
            - bandit              

